defaults:
  - benchmark_schema   # use BenchmarkConfig class as defaults
  - _self_             # then fill in the rest of the args with below

home_dir: "/grand/insitu/cohanlon"
ssd_dir: "/raid/scratch"

# relative to home_dir
data_path: "datasets/raw"
params_path: "kan_inr/params"

enable_pbar: False    # progress bar is written to error file on PBS
repeats: 1            # number of times to repeat each experiment

save_mode: null # save smallest or largest hashtable size for a given dataset INR

# Model(s) to benchmark
network_types: ["fkan", "mlp"]
